### ISSUE TITLE
Datepicker in Admin

### ISSUE THREAD

**Issue by ledviaggi** [app-generator/django-admin-argon2-pro#1]
Hi!
I'm having an issue on the Admin pages. 
When I create new models having DateTime field, on the Admin interface this field is not mapped on a DatePicker control.

News model:
`class News(models.Model):
    text = models.TextField()
    date = models.DateTimeField()`

![image](https://github.com/app-generator/django-admin-argon2-pro/assets/127018236/baf1b93b-a58c-4252-9ecc-09321f34fefd)

**Comment by app-generator** [comment]
Hello @ledviaggi 

The fix is delivered in version `v1.0.9`.
Please pull the latest version and test.
